#!/bin/sh

GIT_DIR=`git rev-parse --show-toplevel`/.git
TEMP_BRANCH_NAME=`uuidgen`

#git checkout -b $TEMP_BRANCH_NAME

START_COMMIT=`git rev-parse $1`

java -jar $HOME/bin/rebaser.jar $GIT_DIR $START_COMMIT
